services:
  - type: web
    name: kotla-medicals
    runtime: node
    region: singapore
    plan: free
    buildCommand: bun install --frozen-lockfile && bun run build
    startCommand: bun run start
